project_id = "bbffmosouvzifowfwwzk"

[functions.dob-violations]
verify_jwt = false

[functions.geocode]
verify_jwt = false

[functions.dob-ecb]
verify_jwt = false

[functions.dob-permits]
verify_jwt = false

[functions.dob-safety]
verify_jwt = false

[functions.hpd-violations]
verify_jwt = false

[functions.hpd-complaints]
verify_jwt = false

[functions.service-requests-311]
verify_jwt = false
